# instructions: https://man.sr.ht/git.sr.ht/#setting-a-custom-readme
image: freebsd/13.x
packages:
  - hs-pandoc
  - jq
secrets:
  - 804d8ca2-529a-4761-b5a5-79b0c9092336
sources:
  - https://git.sr.ht/~ashton314/adapton
environment:
  repo_id: 142549
  readme: "/tmp/readme.html"
tasks:
  - build: |
      cd adapton
      pandoc README.org -o $readme
  - publish: |
      jq -sR '{
          "query": "mutation UpdateRepo($id: Int!, $readme: String!) {
            updateRepository(id: $id, input: { readme: $readme }) { id }
          }", "variables": {
            "id": '$repo_id',
            "readme": .
          } }' < $readme \
        | curl --oauth2-bearer $(cat ~/.build-secret) \
          -H "Content-Type: application/json" \
          -d@- https://git.sr.ht/query
